routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PagesController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\BlogController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/blog/{slug}', [BlogController::class, 'getSingle'])
    ->name('blog.single')
    ->where('slug', '[\w\d\-\_]+');
Route::get('/contact', [PagesController::class, 'getContact']);
Route::get('/about', [PagesController::class, 'getAbout']);
Route::get('/', [PagesController::class, 'getIndex']);
Route::resource('posts', PostController::class);

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Pagination\Paginator;

class Post extends Model
{
    use HasFactory;
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/BlogController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Post;

class BlogController extends Controller
{
    public function getSingle($slug) {
        // fetch from the DB based on slug
        $post = Post::where('slug', '=', $slug)
            ->first();
        // return the view and pass in the post object
        return view('blog.single')
            ->withPost($post);
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/PagesController.php
<?php

namespace App\Http\Controllers;

use App\Models\Post;

class PagesController extends Controller {

    public function getIndex() {
        $posts = Post::orderBy('created_at', 'desc')
            ->limit(4)
            ->get();
        return view('pages.welcome')
            ->withPosts($posts);
    }

    public function getAbout() {
        $first = 'Pete';
        $last = 'Vanliere';

        $fullname = $first . " " . $last;
        $email = 'pete@monitorbase.com';
        $data = [];
        $data['email'] = $email;
        $data['fullname'] = $fullname;
        return view('pages.about')->withData($data);
    }

    public function getContact() {
        return view('pages.contact');
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller; /** Saw this use in the video but I don't know if I need it */
use App\Models\Post;
use Session;


class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // create a variable and store all the blog posts in it from the DB
        $posts = Post::orderBy('id', 'desc' )
            ->paginate(10);

        // return a view and pass in the above variable
        return view('posts.index')->withPosts($posts);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('posts.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // validate the data

        $request->validate([
            'title' => 'required|max:255',
            'slug' => 'required|alpha_dash|min:5|max:255|unique:posts,slug',
            'body' => 'required',

        ]);

        // store in the database

        $post = new Post;

        $post->title = $request->title;
        $post->slug = $request->slug;
        $post->body = $request->body;

        $post->save();

        Session::flash('success', 'The Blog post was successfully saved!');

        // redirect to another page
        return redirect()->route('posts.show', $post->id);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $post =  Post::find($id);
        return view('posts.show')->withPost($post);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        // find the post in the database and save it as a variable
        $post = Post::find($id);

        // return the view and pass in that information we previously created
        return view('posts.edit')->withPost($post);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        // Validate the data
        $request->validate([
            'title' => 'required|max:255',
            'slug' => 'required|alpha_dash|min:5|max:255|unique:posts,slug',
            'body' => 'required',
        ]);

        // Save the data to the DB

        $post = Post::find($id);

        $post->title = $request->input('title');
        $post->slug = $request->input('slug');
        $post->body = $request->input('body');

        $post->save();

        // set flash data with success message
        Session::flash('success', 'This post was successfully updated!');

        // Redirect with flash data to posts.show

        return redirect()->route('posts.show', $post->id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $post = Post::find($id);

        $post->delete();

        Session::flash('success', 'The post was successfully deleted!');

        return redirect()->route('posts.index');

    }
}

resources/views/blog/single.blade.php
@extends('main')

@section('title', "| $post->title")

@section('content')

    <div class="p-10 text-4xl text-center">{{$post->title}}</div>
    <div class="p-4 border-2 border-slate-200">{{$post->body}}</div>

@endsection

resources/views/main.blade.php
<!doctype html>
<html>
    <head>
        @include('partials._head')
    </head>
    <body class="bg-gradient-to-r from-slate-100 to-slate-300">
        @include('partials._messages')
        @include('partials._nav')
        @yield('content')
        @include('partials._footer')
    </body>
</html>

resources/views/pages/about.blade.php
@extends('main')

@section('title', '| About')

@section('content')

<div>Have to fill this out at some point</div>

@endsection

resources/views/pages/contact.blade.php
@extends('main')

@section('title', '| Contact')

@section('content')

<div> Contact me, or not </div>

<div class="text-lg"> Test for classes</div>

<div class="flex flex-auto w-full text-center p-4">
    <form>
        <label>Email:</label>
        <input class="border-2 px-4" id="email">
        <label>Subject:</label>
        <input class="border-2 px-4" id="subject">
        <div class="p-4 justify-end">
        <textarea class="border-2 p-4" id="message">Tell me a joke... not a funny one</textarea>
        </div>
        <input type="submit" value="Send Message" class="bg-green-600 hover:bg-green-900 p-4" text="Button">
    </form>
</div>

@endsection

resources/views/partials/_footer.blade.php
<div class="flex flex-row justify-center w-full pt-4 text-xs">
    <div>Footer but no feet stuff, yuck.</div>
</div>

resources/views/partials/_head.blade.php
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script src="https://cdn.tailwindcss.com"></script>
  <title>Laravel Blog @yield('title')</title>

resources/views/partials/_messages.blade.php
@if (Session::has('success'))

    <div class="text-center border bg-amber-400">
        <div class="text-xl font-bold text-red-700"> IT WORKED!</div>
        <div> {{ Session::get('success') }}</div>
    </div>
@endif

@if (count($errors) > 0)

    <div class="text-center border bg-amber-400">
        <div class="text-xl font-bold text-red-700"> IT HAS ERRORS!</div>
        @foreach ($errors->all() as $error)
            <div>{{ $error }}</div>
        @endforeach
    </div>
@endif

resources/views/partials/_nav.blade.php
<div class="flex flex-col w-full p-8 text-center bg-gradient-to-r from-transparent via-orange-200">
    <div class="text-4xl">WARM FIRE HERE</div>
    <div class="text-base">not an angelfire, but a demonfire...</div>
</div>

<div class="h-5 border-b-2 rounded-b-full border-slate-200 bg-gradient-to-r from-transparent via-orange-200 "></div>

<div class="flex justify-center p-4 px-4 text-lg text-blue-500">
  <a class="px-7 hover:bg-yellow-100 rounded-lg {{ (request()->is('/')) ? 'rounded-lg bg-slate-300 text-blue-700' : ''}}" href="/">Home</a>
  <a class="px-7 hover:bg-yellow-100 rounded-lg {{ (request()->is('about')) ? 'rounded-lg bg-slate-300 text-blue-700' : ''}}" href="/about">About</a>
  <a class="px-7 hover:bg-yellow-100 rounded-lg {{ (request()->is('contact')) ? 'rounded-lg bg-slate-300 text-blue-700' : ''}}" href="/contact">Contact</a>
  <a class="px-7 hover:bg-yellow-100 rounded-lg {{ (request()->is('posts')) ? 'rounded-lg bg-slate-300 text-blue-700' : ''}}" href="/posts">All Posts</a>
</div>

resources/views/posts/create.blade.php
@extends('main')

@section('title', '| Create New Post')

@section('content')

<div class="grid p-4 m-4 text-center cols-2 outline">

    <div class="text-xl">Create New Post!</div>

    <form method="POST" action="{{ route('posts.store') }}" accept-charset="UTF-8">
         @csrf


    <div class="flex w-full text-center">
      <!--  <div class="w-1/2 bg-orange-300">A</div>  -->
        <label class="w-1/4 text-right">Title</label>
        <input class="w-1/2 border-2" name="title" type="text" id="title">
    </div>

    <div class="flex w-full text-center">
      <!--  <div class="w-1/2 bg-orange-300">A</div>  -->
        <label class="w-1/4 text-right">Slug</label>
        <input class="w-1/2 border-2" name="slug" type="text" id="slug" minlength="5" maxlength="255">
    </div>

<!-- Get rid of this one for the moment
        <label for="body">DO I Need this lable?</label>
-->
        <div class="flex flex-row m-4 focus:outline-none focus:ring focus:ring-violet-300">
            <label class="w-24 text-lg" for="body"></label>
            <textarea class="p-4 text-lg" id="body" name="body" rows="10" cols="75">
            </textarea>
        </div>


    <!--  Leave this one here for the one that used to work after I work on the slug stuff

        <label for="body">Post Body</label>
        <input class="px-4 border-2" name="body" type="text" id="body"> -->


        <input type="submit" value="Create Post" class="p-4 bg-green-600 hover:bg-green-900">

    </form>
</div>


@endsection

resources/views/posts/edit.blade.php
@extends('main')

@section('title', '| Edit Blog Post')

@section('content')



<form method="POST" action="{{ route('posts.update', $post->id) }}" accept-charset="UTF-8">
@csrf
@method('PUT')

<div class="p-10">
    <div>
        <div class="flex flex-row m-4">
            <label class="w-24 text-lg" for="title">New Title:</label>
            <input class="px-4 border-2" value="{{$post->title}}" name="title" type="text" id="title">
        </div>

        <div class="flex flex-row m-4">
            <label class="w-24 text-lg" for="title">New Slug:</label>
            <input class="px-4 border-2" value="{{$post->slug}}" name="slug" type="text" id="slug">
        </div>

        <div class="flex flex-row m-4 focus:outline-none focus:ring focus:ring-violet-300">
            <label class="w-24 text-lg" for="body">New Body</label>
            <textarea class="p-4 text-lg" id="body" name="body" rows="10" cols="75">
            {{$post->body}}
            </textarea>
        </div>
    </div>

    <div class="text-center">
        <div>Created at: {{ date( 'M j, Y h:i a', strtotime($post->created_at)) }}</div>
        <div>Last Updated: {{ date( 'M j, Y h:i a', strtotime($post->updated_at)) }}</div>
    </div>

    <div><!-- Just a blank div to keep the grid working -->
    </div>

    <div class="p-4 m-4 text-center">
        <a class="p-4 text-white bg-red-600 rounded hover:bg-red-800 hover:border-4 hover:border-black" href="{{ route('posts.show', $post->id)}}">Cancel</a>
        <input type="submit" value="Save Changes" class="p-4 text-white bg-green-400 rounded hover:bg-green-900 hover:border-4 hover:border-black">
    </div>
</div>
</form>



@endsection

resources/views/posts/index.blade.php
@extends('main')

@section('title', '| All Posts')

@section('content')

<div class='flex flex-row m-4 border-2 justify-evenly'>

    <div class="p-4">All Posts
    </div>

    <div class="p-4 text-right">
        <a class="p-1 m-2 text-white align-top bg-green-400 border-2 rounded-lg" href="{{ route('posts.create')}}">Create a post</a>
    </div>

</div>

<div class="flex flex-row w-full p-4 border-2 border-slate-200">
    <div class="w-1/4 text-3xl text-right">All Posts:</div>
       <!-- <div class="text-2xl bg-red-400 ">All Posts</div> -->
    <div class="w-2/4"></div>
    <div class="w-1/4">
        <a class="p-1 text-white bg-green-400 border-2 rounded-lg border-slate-400" href="{{ route('posts.create')}}">Write New Post</a>
    </div>
</div>

<div class="flex justify-center flex-auto">
    <table class="justify-center p-4 text-center table-fixed border-slate-400">

        <thead class="border bg-gradient-to-r from-slate-500">
            <tr class="">
                <th>ID</th>
                <th>Title</th>
                <th>Body</th>
                <th>Created at</th>
                <th></th>
            </tr>
        </thead>

        <tbody class="border border-red-300">
            @foreach($posts as $post)
                <tr class="border">
                    <td class="p-4">{{$post->id}}</td>
                    <td class="text-right">{{$post->title}}</td>
                    <td class="p-4 m-4">{{ substr($post->body, 0, 50 )}}{{ strlen($post->body) > 50 ? "..." : "" }}</td>
                    <td class="p-4 m-4">{{ date('M j, Y', strtotime($post->created_at))}}</td>
                    <td><a class="px-4 m-2 text-white bg-orange-200 border-2 rounded-lg hover:bg-orange-500 border-slate-400" href="{{ route('posts.show', $post->id)}}">View</a>
                        <a class="px-4 m-2 text-white border-2 rounded-lg border-slate-400 bg-emerald-300 hover:bg-emerald-500" href="{{ route('posts.edit', $post->id)}}">Edit</a>
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>
</div>


<!--This is the nav for pagination -->

<div class="flex justify-center">
{{ $posts->links() }}
</div>

@endsection

resources/views/posts/show.blade.php
@extends('main')

@section('title', '| View Post')

@section('content')
<div class="grid grid-cols-2 p-2 m-4 border-2 ">
    <div class="pr-10 text-xl text-right">
        <div>Title:</div>
        <div>Slug:</div>
        <div>Body:</div>
    </div>

    <div>
        <div>{{ $post->title }}</div>
        <div class="text-blue-400"><a href="{{ route('blog.single', $post->slug) }}">{{ route('blog.single', $post->slug) }}</div>
        <div>{{ $post->body }}</div>
    </div>

    <div class="pr-10 text-right">
        <div>Created at: {{ date( 'M j, Y h:i a', strtotime($post->created_at)) }}</div>
        <div>Last Updated: {{ date( 'M j, Y h:i a', strtotime($post->updated_at)) }}</div>
    </div>

    <div>
        <a class="px-4 m-4 text-white bg-green-400 rounded hover:bg-green-700" href="/posts/{{$post->id}}/edit">Edit</a>

        <form action="{{ route('posts.destroy', $post->id) }}" type="submit" method="post" accept-charset="UTF-8">
            @method('delete')
            @csrf
            <input type="submit" value="Delete Post" class="px-4 m-4 text-white bg-red-600 rounded hover:bg-red-900">
        </form>

    </div>
</div>

@endsection